---
title: "About This Website"
---

I created this website as part of my work in the [Open Science Fellow Program](https://wikimedia.de/wiki/BildungWissenschaftKultur/Fellowprogramm/Fellows). Open Science needs communication, and what better way could there be than making your science explorable online? While learning to use GitHub, I stumbled across GitHub Pages, which resulted in this webpage.

Please note that besides presenting my project, this page is also my GitHub and GitHub Pages playground, therefore things are often under construction.

# About me
I got a master's degree in Organismic Biology and Evolution from the Humboldt Universität zu Berlin. Spending my master`s thesis at the Museum für Naturkunde I got interested in paleontology and the possibility to learn from the fossil record. Aiming at connecting the fossil record with questions from today's species, I started my PhD on traits that influence extinction risk in fossil and modern amphibian species at the [Museum für Naturkunde](https://www.naturkundemuseum.berlin/en/einblicke/mitarbeiter/melanie.tietje) in 2014.