---
title: "About me"
comments: true
---


I got a master's degree in Organismic Biology and Evolution from the Humboldt Universität zu Berlin. Spending my master`s thesis at the Museum für Naturkunde I got interested in paleontology and the possibility to learn from the fossil record. Aiming at connecting the fossil record with questions from today's species, I started my PhD on traits that influence extinction risk in fossil and modern amphibian species at the [Museum für Naturkunde](https://www.naturkundemuseum.berlin/en/einblicke/mitarbeiter/melanie.tietje) in 2014.


I became a fellow in the fellow program open science in September 2016, since then I am exploring certain aspects of open science like community feedback in data analysis and publication. 

A description of the program and the other fellows and their projects can be found here:
[Fellow Program Open Science](https://wikimedia.de/wiki/BildungWissenschaftKultur/Fellowprogramm/Fellows)


# Comments 
Leave a comment on this page!
```{r, echo=FALSE}
htmltools::includeHTML("_layouts/disqus.html")

```