---
title: "Contact"
---


* melanie.tietje[AT]mfn-berlin.de
* [GitHub](https://github.com/Eryops1)
* [Museum für Naturkunde](https://www.naturkundemuseum.berlin/en/einblicke/mitarbeiter/melanie.tietje)
* [ResearchGate](https://www.researchgate.net/profile/Melanie_Tietje)
* [Publons](https://publons.com/author/1629562/melanie-tietje#profile)

-----

# Collaborators

### The herpetology lab at Natural History Museum Berlin

My [lab at the museum](https://www.researchgate.net/lab/Mark-Oliver-Roedel-Lab). Frog experts, snake enthusiasts and allround ecologists.


### Martin Schobben

[Geobiologist at Utrecht University](https://martinschobben.github.io/webpage/index.html), The Netherlands. He works on the interaction of organisms with their environment, the large biogeochemical cycles and climate, during pivotal periods in the Earths’ history. Recently he focuses on developing methodological strategies to reliably read these geochemical proxies in terms of the recorded physical and chemical parameters.

### Richard Hofmann

[Palaeontologist at Museum für Naturkunde Berlin](http://www.fossilrich.com/), Germany. He is nterested in fundamental transformations (i.e. mass extinctions, recovery episodes, radiations, and ecological innovation).

### Johan Renaudie

[Micropaleontologist at Museum für Naturkunde Berlin](https://plannapus.github.io/
), Germany. He studies Cenozoic siliceous plankton and their relationship with past climatic and oceanographic changes, and our R-hero.



<!-- # Comments  -->
<!-- Leave a comment on this page! -->
<!-- ```{r, echo=FALSE} -->
<!-- # this html includes disqus -->
<!-- #htmltools::includeHTML("_layouts/disqus.html") -->

<!-- # this includes the html comment box -->
<!-- htmltools::includeHTML("_layouts/post.html") -->

<!-- ``` -->