---
output:
  html_document:
    toc: no
    toc_float: true
    toc_depth: 2
---

# Research experience and projects

**2025 - ongoing: Postdoc**\
Czech University of Life Sciences in Prague, Czech Republic\
[Modelling of Biodiversity Lab (MOBI Lab)](https://petrkeil.github.io/) (PI: Petr Keil)\
Project: BEAST: Biodiversity dynamics across a continuum of space, time, and their scales (ERC)


**2024: Postdoc**\
Temple University, Philadelphia, USA\
[Center for Biodiversity](http://www.biodiversitycenter.org/people) (PI: Blair Hedges)\
Project: Forecasting functional biodiversity change with satellite remote sensing and modeling (NSF)


**2019 - 2023: Postdoc**\
Aarhus University, Denmark\
Section for Ecoinformatics and Biodiversity, [Plant Evolution and Biodiversity](https://bio.au.dk/en/research/research-areas/genetics-and-evolution/plant-evolution-and-biodiversity) (PI: Wolf Eiserhardt)\
Project: TropiToL - Explaining the biological hyperdiversity of Tropical rainforests using the Tree of Life (Villum Fonden)

**2018 - 2019: Research assistant**\
Natural History Museum Berlin, [Herpetology](https://www.museumfuernaturkunde.berlin/en/science/reptiles-and-amphibians)\
Data analysis for amphibian monitoring project in the Nimba Mountains, Guinea

**2014 – 2018: Doctoral candidate**\
Humboldt Universität zu Berlin | Natural History Museum Berlin\
Project: Combining paleontological and neontological data to assess the extinction risk of amphibians

**2012 - 2013: Research assistent**
Natural History Museum Berlin, Paleoecology\
Project: Geographic range dynamics of marine invertebrates


**2008: Field work assistant**\
Humboldt Universität zu Berlin, Behavioural Physiology\
Navigation mechanisms of Cataglyphis fortis in Tunisia


# Education

**2014 – 2018: Doctoral candidate**\
Humboldt Universität zu Berlin | Natural History Museum Berlin\
Thesis title: Combining paleontological and neontological data to assess the extinction risk of amphibians\
Degree: Dr. rer. nat. (summa cum laude)

**2008 – 2011: Master student**\
Humboldt Universität zu Berlin\
MSc Organismic Biology and Evolution\
Degree: Master of Science (1.3, very good)

**2005 – 2008: Bachelor student**\
Humboldt Universität zu Berlin\
BSc Biology\
Degree: Bachelor of Science (2.3, good)


# Languages
* German (first language)
* English (business fluent)
* French (basic knowledge)
* Danish (basic knowledge)


# Grants 

* MfN Innovationsfond (Natural History Museum Berlin Berlin, institute internal grant): Linking climate trends with the amphibian fossil record
* Fellow Program Open Science by Wikimedia and Stifterverband: Opening up science
* Travel Grant Progressive Palaeontology Conference 2016
* Elsa Neumann Fellowship of the state of Berlin: A paleontological-zoological analysis of the influence of traits on the extinction risk of amphibians


# Commitee work

2014 - 2017: Elected member of the representation of doctoral researchers at Natural History Museum Berlin\
2007 - 2011: Student council at the Humboldt University of Berlin


# Software and programming 

* LaTeX\
* Inkscape, GIMP, Photoshop (basics)\
* QGIS, BEAST, Tracer, Mesquite, GPlates, Git(Hub)\
* BASH for SLURM managed clusters\
* R (12+ years experience. Spatial and phylogenetic data. Data analysis, statistics, visualization, Markdown, structural equation models, gradient boosting machines and other machine learning, trait evolution models; e.g. Mk-models, state-dependent speciation and extinction models)\
* Java Script (basics to get by in Google Earth Engine)\
* Python (basics)

