---
title: ""
# output:
#   html_document:
#     toc: no
#     toc_float: true
#     toc_depth: 2

---  

<!-- # Publications -->

#### In Review
Tietje M, Grattarola F, Ortega-Solis G, Soria C, Tschernosterová K, Leroy F, Bejček V, Šťastný K, Herrando S, Keller V, Keil P. Bird co-occurrences remain largely stable in a changing world. Manuscript resubmitted to **Nature** following peer review.

Ortega-Solís G, Šťastný K, Bejček V, Telenský T, Mellado-Mansilla D, Zárybnicky J, Grattarola F, Zárybnická M, Vermouzek Z, Voříšek P, Leroy F, Tietje M, Soria C, Padulosi E, Trávníčková E, Wölke FJR, Keil P. Opening a standardized, spatially contiguous biodiversity database collected over 40 years: Czech breeding bird atlases 1973—77, 1985—89, 2001—03, and 2014—17. **Journal of Biogeography**, preprint; [https://doi.org/10.64898/2026.05.29.728651](https://doi.org/10.64898/2026.05.29.728651)

------------

#### 2026

Grattarola F, Ortega-Solís G, Soria C, Tietje M, Wölke FJR, Fox R, Hordley L, Herrando S, Keil P. Probabilistic species distributions from nine large-scale gridded atlases over five decades. preprint on bioRxiv: [https://doi.org/10.64898/2026.09.24.754027](https://doi.org/10.64898/2026.09.24.754027)

Hedges S, Hong F, Su JW, Tietje M, Guillory W, Yang Z, Brooks T, Zhu Z. A System for Global Forecasting of Species Extinction Risk and Protected Area Effectiveness. Available at SSRN: [http://dx.doi.org/10.2139/ssrn.6690553](http://dx.doi.org/10.2139/ssrn.6690553)

#### 2024
Bergman J, Pedersen RØ, Lundgren EJ, Trepel J, Pearce EA, Czyżewski S, Tietje M, Lemoine RT, Macià MC, Schierup MH, Svenning J-C. Trade-offs beget trade-offs: Causal analysis of mammalian population dynamics. **bioRxiv** 2024.08.16.608243; doi: [https://doi.org/10.1101/2024.08.16.608243](https://doi.org/10.1101/2024.08.16.608243) 

Wrisberg O, Petoe P, Bacon CD, Bellot S, Baker WJ, Cano A, Couvreur TLP, Dransfield J, Ferreira P, Henderson A, Stauffer F, Tietje M, Weigelt P, Eiserhardt WL (**in prep**) Effects of Area, Isolation and Elevation on Island Plant speciation. 

Trepel J, Abraham AJ, Lundgren EJ, Ferraro KM, Fløjgaard C, Haugaard L., Sunde P, Pedersen RØ, Tietje M, Kamp J, & le Roux E (2024). Zoogeochemistry of a protected area: Driven by anthropogenic impacts and animal behavior. **Conservation Science and Practice**, 6(5). [https://doi.org/10.1111/csp2.13107](https://doi.org/10.1111/csp2.13107)

Trepel J, le Roux E, Abraham AJ, Buitenwerf R, Kamp J, Kristensen JA, Tietje M, Lundgren EJ, Svenning J-C (2024). Meta-analysis shows that wild large herbivores shape ecosystem properties and promote spatial heterogeneity. **Nature Ecology & Evolution**. [https://doi.org/10.1038/s41559-024-02327-6](https://doi.org/10.1038/s41559-024-02327-6)

Lundgren EJ, Bergman J, Trepel J, le Roux E, Monsarrat S, Kristensen JA, Pedersen RØ, Pereyra P, Tietje M, Svenning J-C. (2024). Functional traits-not nativeness-shape the effects of large mammalian herbivores on plant communities. **Science** 383: 531–537. [https://doi.org/10.1126/science.adh2616](https://doi.org/10.1126/science.adh2616)


#### 2023
Tietje, M., Antonelli, A., Forest, F., Govaerts, R., Smith, S.A., Sun, M., Baker, W.J. and Eiserhardt, W.L. (2023), Global hotspots of plant phylogenetic diversity. **New Phytologist** [https://doi.org/10.1111/nph.19151](https://doi.org/10.1111/nph.19151)

Maitner, B., Gallagher, R., Svenning, J.-C., Tietje, M., Wenk, E.H. and Eiserhardt, W.L. (2023), A global assessment of the Raunkiæran shortfall in plants: geographic biases in our knowledge of plant traits. **New Phytologist** [https://doi.org/10.1111/nph.18999](https://doi.org/10.1111/nph.18999)

Antonelli A, Fry C, Smith RJ, Eden J, Govaerts RHA, Kersey P, Nic Lughadha E, Onstein RE, Simmonds MSJ, Zizka A, Ackerman JD, Adams VM, Ainsworth AM, Albouy C, Allen AP, Allen SP, Allio R, Auld TD, Bachman SP, ... Zuntini AR (2023). **State of the World's Plants and Fungi, 2023**: Tackling the Nature Emergency: Evidence, Gaps and Priorities. Royal Botanic Gardens, Kew. [https://doi.org/10.34885/WNWN-6S63](https://doi.org/10.34885/WNWN-6S63)

#### 2022
Tietje, M., Antonelli, A., Baker, W. J., Govaerts, R., Smith, S. A., & Eiserhardt, W. L. (2022). Global variation in diversification rate and species richness are unlinked in plants. **PNAS**, 119(27), e2120662119. [https://doi.org/10.1073/pnas.2120662119](https://www.pnas.org/doi/full/10.1073/pnas.2120662119)

Rudbeck, A.V., Sun, M., Tietje, M., Gallagher, R.V., Govaerts, R., Smith, S.A., Svenning, J.-C. and Eiserhardt, W.L. (2022), The Darwinian shortfall in plants: phylogenetic knowledge is driven by range size. **Ecography** e06142. [https://doi.org/10.1111/ecog.06142](https://doi.org/10.1111/ecog.06142)

Dittrich, C., Tietje, M., & Rödel, M. (2022). Larger is not better: no mate preference by European common frog (Rana temporaria) males, **Behaviour** (published online ahead of print 2022). doi: https://doi.org/10.1163/1568539X-bja10169

#### 2021
Hansen, L. E. S., Baker, W. J., Tietje, M., & Eiserhardt, W. L. (2021). Testing tropical biogeographical regions using the palm family as a model clade. **Journal of Biogeography**. [https://doi.org/10.1111/jbi.14216](https://doi.org/10.1111/jbi.14216)

#### 2020
Foster, W. J., Gliwa, J., Lembke, C., Pugh, A. C., Hofmann, R., Tietje, M., Varela, S., Foster, L.C., Korn, D.,Aberhan, M. (2020). Evolutionary and ecophenotypic controls on bivalve body size distributions following the end-Permian mass extinction. **Global and Planetary Change**, 185, 103088. [doi:10.1016/j.gloplacha.2019.103088](https://doi.org/10.1016/j.gloplacha.2019.103088)

Tietje, M., Rödel, M.-O., Schobben, M. (2020). The effect of geographic range and climate on extinction risk in the deep-time amphibian fossil record. **Palaeogeography, Palaeoclimatology, Palaeoecology** [doi:10.1016/j.palaeo.2019.109414](https://doi.org/10.1016/j.palaeo.2019.109414)

#### 2019
Varela, S., Sbrocco, E., Tarroso, P., Pérez-Luque, A.J., Renaudie, J., Warnstädt, N., Fandos, G., Foster, W., Tietje, M. (2019). BioExtreme hackathon en el Museum für Naturkunde de Berlín, Alemania. **Ecosistemas** 28(1): 129. [doi: 10.7818/ECOS.1707](https://www.revistaecosistemas.net/index.php/ecosistemas/article/view/1707)

Hofmann, R., Tietje, M., and Aberhan, M. (2019). Diversity partitioning in Phanerozoic benthic marine communities. **PNAS** [https://www.pnas.org/content/early/2018/12/13/1814487116](https://www.pnas.org/content/early/2018/12/13/1814487116)

#### 2018
Schobben, M. , Heuer, F. , Tietje, M. , Ghaderi, A. , Korn, D. , Korte, C. and Wignall, P. B. (2018). Chemostratigraphy Across the Permian‐Triassic Boundary. In **Chemostratigraphy Across Major Chronological Boundaries** (eds A. N. Sial, C. Gaucher, M. Ramkumar and V. P. Ferreira). [doi:10.1002/9781119382508.ch9](https://doi.org/10.1002/9781119382508.ch9)


Tietje, M. and Rödel, M.-O. (2018). Evaluating the predicted extinction risk of living amphibian species with the fossil record. **Ecology Letters**. [doi:10.1111/ele.13080](https://doi.org/10.1111/ele.13080)

#### 2017
Melanie Tietje, Mark-Oliver Rödel, Contradicting habitat type-extinction risk relationships between living and fossil amphibians. **Royal Society Open Science** 2017 4 170051; [doi: 10.1098/rsos.170051](http://rsos.royalsocietypublishing.org/cgi/content/full/rsos.170051?ijkey=HFAoNHwozz9aFKn&keytype=ref). Published 10 May 2017

#### 2013
Tietje, M. and Kiessling, W. (2013). Predicting extinction from fossil trajectories of geographical ranges in benthic marine molluscs. **Journal of Biogeography**, 40: 790–799. [doi:10.1111/jbi.12030](http://onlinelibrary.wiley.com/doi/10.1111/jbi.12030/abstract)

<br>

---------


# I have been reviewing for:

* Applications in Plant Sciences
* Biology Letters
* Current Zoology 
* Diversity and Distributions
* Ecography
* Ecology Letters
* Global Ecology and Biogegraphy
* New Phytologist
* Palaeontologia Electronica
* Palaeontology
* PeerJ
* Science
